name: LinerRX
version: '@plugin.version@'
main: moe.xmcn.guildbot.qqguildbot.LinerRX
api-version: 1.19
authors: [ XiaMoHuaHuo_CN ]
description: QQ频道机器人
commands:
  qgb:
    description: "LinerRX Commands"
  qqguildbot:
    description: "LinerRX Commands"
permission:
  qqguildbot.*:
    description: "LinerRX Permissions"
    default: false
    children:
      qqguildbot.admin:
        description: "LinerRX Admin Permission"
        default: op
